### ISSUE TITLE
poetry2nix error

### ISSUE THREAD

**Issue by energizah** [tweag/jupyterWith#133]
**Describe the bug**

When I try to build an environment using poetry2nix and jupyterWith, it fails. 

**To Reproduce**
Steps to reproduce the behavior.

Clone [this repo](https://github.com/energizah/poetry2nix-withJupyter-demo) and run 

```
nix-shell --command 'jupyter run --kernel ipython_poetry  <<<"import requests; print(requests)"' --show-trace
```

**Expected behavior**

It should print the repr of the `requests` module.

**What happens instead**

```
/nix/store/p1j3cz54y4jz2s1ajwqpx6mq6kqn9igh-python3.7-traitlets-4.3.3/lib/python3.7/site-packages/traitlets/config/loader.py:795: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
/nix/store/p1j3cz54y4jz2s1ajwqpx6mq6kqn9igh-python3.7-traitlets-4.3.3/lib/python3.7/site-packages/traitlets/config/loader.py:804: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
Traceback (most recent call last):
  File "/nix/store/346skv0d24rqnf4npknbp9h5bs14j8zy-python3-3.8.6/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/346skv0d24rqnf4npknbp9h5bs14j8zy-python3-3.8.6/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nix/store/rgg707my9m2qicm2jxihrl21cmh50mx6-python3.7-ipykernel-5.1.2/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/nix/store/rgg707my9m2qicm2jxihrl21cmh50mx6-python3.7-ipykernel-5.1.2/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/nix/store/rgg707my9m2qicm2jxihrl21cmh50mx6-python3.7-ipykernel-5.1.2/lib/python3.7/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/nix/store/5m9yhim8n97iihy1dz2cx3dl3fvajx0n-python3.7-jupyter_client-5.3.4/lib/python3.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/nix/store/5m9yhim8n97iihy1dz2cx3dl3fvajx0n-python3.7-jupyter_client-5.3.4/lib/python3.7/site-packages/jupyter_client/connect.py", line 24, in <module>
    import zmq
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/backend/cython/__init__.py)
```

**Environment**
 - OS name + version: nixos-unstable

**Comment by guaraqe** [comment]
Hello, I executed the command, and got the following response:
```
<module 'requests' from '/nix/store/iwqvxb95wf5bp05r46g9i462z0wcf6d0-python3.7-requests-2.22.0/lib/python3.7/site-packages/requests/__init__.py'>
```
so it works well for me. I found the following [issue](https://github.com/jupyter/notebook/issues/5543) that seems to present the same behavior you see, and is due to conflicting versions of Python installed. I propose you to check:
- if you have Python and Jupyter installed globally, which may be creating conflicts
- try to execute the same command with `--pure` so that only the dependencies declared are present, which would, in theory, avoid these conflicts

**Comment by energizah** [comment]
I do have Python but not Jupyter installed globally. Running with `--pure` doesn't help.

```
% nix-shell --pure --command 'jupyter run --kernel ipython_poetry  <<<"import requests; print(requests)"' 
/nix/store/p1j3cz54y4jz2s1ajwqpx6mq6kqn9igh-python3.7-traitlets-4.3.3/lib/python3.7/site-packages/traitlets/config/loader.py:795: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
/nix/store/p1j3cz54y4jz2s1ajwqpx6mq6kqn9igh-python3.7-traitlets-4.3.3/lib/python3.7/site-packages/traitlets/config/loader.py:804: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
Traceback (most recent call last):
  File "/nix/store/346skv0d24rqnf4npknbp9h5bs14j8zy-python3-3.8.6/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/346skv0d24rqnf4npknbp9h5bs14j8zy-python3-3.8.6/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nix/store/rgg707my9m2qicm2jxihrl21cmh50mx6-python3.7-ipykernel-5.1.2/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/nix/store/rgg707my9m2qicm2jxihrl21cmh50mx6-python3.7-ipykernel-5.1.2/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/nix/store/rgg707my9m2qicm2jxihrl21cmh50mx6-python3.7-ipykernel-5.1.2/lib/python3.7/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/nix/store/5m9yhim8n97iihy1dz2cx3dl3fvajx0n-python3.7-jupyter_client-5.3.4/lib/python3.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/nix/store/5m9yhim8n97iihy1dz2cx3dl3fvajx0n-python3.7-jupyter_client-5.3.4/lib/python3.7/site-packages/jupyter_client/connect.py", line 24, in <module>
    import zmq
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/nix/store/rmds624lhg7drbkxys28q61szpxid68k-python3.7-pyzmq-18.1.0/lib/python3.7/site-packages/zmq/backend/cython/__init__.py)
^C^\%         
```

**Comment by guaraqe** [comment]
I am not sure how to help, but the multiple Python theories at the same time theory makes sense. Looking at your error messages you see:
```
  File "/nix/store/346skv0d24rqnf4npknbp9h5bs14j8zy-**python3-3.8.6**/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nix/store/rgg707my9m2qicm2jxihrl21cmh50mx6-**python3.7**-ipykernel-5.1.2/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
```
If you are able to track why you have both these versions accessible at the same time (maybe some ENV variables in the bashrc?), that will help you solve the problem.

**Comment by stolyaroleh** [comment]
`poetry2nix` is likely using Python 3.8 while `jupyterWith` uses 3.7. `iPythonWith` just computes a union of IPython and whatever packages you provide.
I solved this problem by pinning a version of `nixpkgs` and then adding `poetry2nix` and `jupyterWith` using an overlay.
This ensures that both of them use the exact same version of Python.
```nix
self: super:
let
  jupyterWithSrc = builtins.fetchGit { ... };
  poetry2nixSrc = builtins.fetchGit { ... };
  # Apply upstream overlay since it introduces some Python packages Jupyter relies on.
  python = import (jupyterWithSrc + /nix/python-overlay.nix) self super;
in
python //
{
  jupyterWith = import jupyterWithSrc { pkgs = super; };
  poetry = super.callPackage (poetry2nixSrc + /pkgs/poetry) {
    python = self.python3;
  };

  poetry2nix = import poetry2nixSrc {
    inherit (super) pkgs;
    inherit (self) poetry;
  };
}
```

**Comment by l0b0** [comment]
@energizah Did that suggestion work for you? I can't seem to get anything like that to build.

**Comment by guaraqe** [comment]
@l0b0 We have an example of using Poetry in `examples/Python`, does it work for you? Make sure to use the last commit in the repo.

**Comment by l0b0** [comment]
I was hoping to pull the package list out of the Poetry env rather than having to process pyproject.toml, effectively duplicating what Poetry does.
