### ISSUE TITLE
doc/adding extensions

### ISSUE THREAD

**Issue by djacu** [tweag/jupyterWith#222]
### Overview
There are [two ways](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#overview-of-extensions) to distribute extensions. A source extension is a JavaScript (npm) package that exports one or more plugins. Installing a source extension requires a user to rebuild JupyterLab. This rebuilding step requires Node.js and may take a lot of time and memory. A prebuilt extension distributes a bundle of JavaScript code prebuilt from a source extension that can be loaded into JupyterLab without rebuilding JupyterLab. Installing a prebuilt extensions does not require Node.js.

### Prebuilt Extensions
See [here](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#output-directory) and [here](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#distributing-a-prebuilt-extension).

To distribute a prebuilt extension, copy its [output directory](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#outputdir) to a location where JupyterLab will find it. The documentation says typically in `<sys-prefix>/share/jupyter/labextensions/<package-name>` but does not specify whether that is a jupyter or jupyterlab directory. However, [this page](https://docs.jupyter.org/en/latest/use/jupyter-directories.html#envvar-JUPYTER_PATH) from the jupyter docs says
> Jupyter uses a search path to find installable data files, such as [kernelspecs](https://jupyter-client.readthedocs.io/en/latest/kernels.html#kernelspecs) and notebook extensions.

and also there is the similar `{sys.prefix}/share/jupyter` path in the table, so we should likely put extensions in the data file path. A copy of the `package.json` file with additional build metadata should be put in this output directory. JavaScript and other files that will be served are put into the `static` subdirectory.

It is unclear but possible that a modified version of this needs to be added to the `package.json` file.
```json
"jupyterlab": {
  "outputDir": "mypackage/labextension"
}
```

**Comment by djacu** [comment]
To see where jupyter installs extensions, I've temporarily created a stateful virtual environment (named `venv`) where I can install extensions using `jupyter-labextension install`. I am looking at the [jupyterlab_email](https://github.com/timkpaine/jupyterlab_email) extension. In the `setup.py`, there is `builder = npm_builder(build_cmd="build", path=jshere)` where `jshere` points to the `js` directory at the top level. [This file](https://github.com/jupyter/jupyter-packaging/blob/9cd61a023f8439c4d46232bb9da39517dbdeccdd/jupyter_packaging/setupbase.py#L165) in `jupyter-packaging` has the `npm_builder` function as well as many other things used in `setup.py`.

Inspecting the `js` directory there are a few key files: `package.json`, `src/index.js`, and `style/index.css`. Following the [Build Process](https://jupyterlab.readthedocs.io/en/stable/user/directories.html#jupyterlab-build-process) section from the JupyterLab documentation, we see that files should be moved into a `staging` directory for processing and then moved to a `static` directory. Looking in the virtual environment we see this:

```shell
$ ls -FhoR venv/share/jupyter/lab/staging/node_modules/jupyterlab_email/
venv/share/jupyter/lab/staging/node_modules/jupyterlab_email/:
total 43K
drwxr-xr-x 2 bakerdn    5 Jul 11 18:09 lib/
-rw-r--r-- 1 bakerdn 2.2K Jul 11 16:17 package.json
drwxr-xr-x 2 bakerdn    3 Jul 11 18:09 style/

venv/share/jupyter/lab/staging/node_modules/jupyterlab_email/lib:
total 27K
-rw-r--r-- 1 bakerdn 1.9K Jul 11 16:17 index.d.ts
-rw-r--r-- 1 bakerdn  14K Jul 11 16:17 index.js
-rw-r--r-- 1 bakerdn  29K Jul 11 16:17 index.js.map

venv/share/jupyter/lab/staging/node_modules/jupyterlab_email/style:
total 9.0K
-rw-r--r-- 1 bakerdn 1.1K Jul 11 16:17 index.css
```

I'm not sure why but all the files show above are archived in another directory.
```shell
$ ls -Fho venv/share/jupyter/lab/extensions/
total 17K
-rw-r--r-- 1 bakerdn 12K Jul 11 18:09 jupyterlab_email-0.2.4.tgz
```

There is a `static` directory in `venv/share/jupyter/lab/static/` with 246 files populated mostly with `.js` and `.js.map` files. None of them appear to be `jupyterlab_email` files but perhaps they are dependencies? Running `jupyter labextension list --debug` points us back to where we saw the archved file.

```shell
$ venv/bin/jupyter-labextension list --debug
Searching ['/home/bakerdn/scratch', '/home/bakerdn/.jupyter', '/home/bakerdn/scratch/venv/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /home/bakerdn/scratch/venv/etc/jupyter
Looking for jupyter_config in /home/bakerdn/.jupyter
Looking for jupyter_config in /home/bakerdn/scratch
Looking for lab_config in /etc/jupyter
Looking for lab_config in /usr/local/etc/jupyter
Looking for lab_config in /home/bakerdn/scratch/venv/etc/jupyter
Looking for lab_config in /home/bakerdn/.jupyter
Looking for lab_config in /home/bakerdn/scratch
Yarn configuration loaded.
Paths used for configuration of page_config: 
	/etc/jupyter/labconfig/page_config.json
Paths used for configuration of page_config: 
	/usr/local/etc/jupyter/labconfig/page_config.json
Paths used for configuration of page_config: 
	/home/bakerdn/scratch/venv/etc/jupyter/labconfig/page_config.json
Paths used for configuration of page_config: 
	/home/bakerdn/.jupyter/labconfig/page_config.json
JupyterLab v3.4.3
Other labextensions (built into JupyterLab)
   app dir: /home/bakerdn/scratch/venv/share/jupyter/lab
        jupyterlab_email v0.2.4 enabled OK
```

**Comment by djacu** [comment]
I am trying to analyze a more simple extension; namely [jupyterlab-theme-solarized-dark](https://github.com/AllanChain/jupyterlab-theme-solarized-dark) which should have a more straightforward build and install process. 

### Install
Installing the theme in my stateful virtual environment.

```shell
$ venv/bin/pip3 install jupyterlab_theme_solarized_dark
Collecting jupyterlab_theme_solarized_dark
  Downloading jupyterlab_theme_solarized_dark-2.1.0-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.7/72.7 kB 4.2 MB/s eta 0:00:00
Installing collected packages: jupyterlab_theme_solarized_dark
Successfully installed jupyterlab_theme_solarized_dark-2.1.0
```

### Output
And looking for instances of this new module.

```shell
$ find . -name "*solarized*"
./venv/share/jupyter/labextensions/jupyterlab-theme-solarized-dark
./venv/share/jupyter/labextensions/jupyterlab-theme-solarized-dark/themes/jupyterlab-theme-solarized-dark
./venv/share/jupyter/lab/staging/node_modules/codemirror/theme/solarized.css
./venv/share/jupyter/lab/staging/node_modules/react-json-tree/src/themes/solarized.ts
./venv/share/jupyter/lab/staging/node_modules/react-json-tree/lib/themes/solarized.d.ts
./venv/share/jupyter/lab/staging/node_modules/react-json-tree/lib/themes/solarized.js
./venv/share/jupyter/lab/staging/node_modules/base16/src/solarized.js
./venv/share/jupyter/lab/staging/node_modules/base16/lib/solarized.js
./venv/lib/python3.9/site-packages/jupyterlab_theme_solarized_dark-2.1.0.dist-info
./venv/lib/python3.9/site-packages/jupyterlab_theme_solarized_dark
./venv/lib/python3.9/site-packages/jupyterlab_theme_solarized_dark/labextension/themes/jupyterlab-theme-solarized-dark
./venv/lib/python3.9/site-packages/nbclassic/static/components/codemirror/theme/solarized.css
```
### labextensions

Okay this is good! We have a directory at `./venv/share/jupyter/labextensions/jupyterlab-theme-solarized-dark` which is exactly where the [documentation](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#distributing-a-prebuilt-extension) says prebuilt extensions should end up. Here is what is in that directory.

```shell
$ ls -FhoAR ./venv/share/jupyter/labextensions/jupyterlab-theme-solarized-dark
./venv/share/jupyter/labextensions/jupyterlab-theme-solarized-dark:
total 61K
-rw-r--r-- 1 bakerdn  22K Jul 13 11:25 build_log.json
-rw-r--r-- 1 bakerdn  223 Jul 13 11:25 install.json
-rw-r--r-- 1 bakerdn 3.5K Jul 13 11:25 package.json
drwxr-xr-x 2 bakerdn   10 Jul 13 11:25 static/
drwxr-xr-x 3 bakerdn    3 Jul 13 11:25 themes/

./venv/share/jupyter/labextensions/jupyterlab-theme-solarized-dark/static:
total 72K
-rw-r--r-- 1 bakerdn 1.7K Jul 13 11:25 lib_index_js.88cfd94f93ca3056743b.js
-rw-r--r-- 1 bakerdn 1000 Jul 13 11:25 lib_index_js.88cfd94f93ca3056743b.js.map
-rw-r--r-- 1 bakerdn 1.7K Jul 13 11:25 lib_index_js.a9f045a011f6eaf91a60.js
-rw-r--r-- 1 bakerdn  985 Jul 13 11:25 lib_index_js.a9f045a011f6eaf91a60.js.map
-rw-r--r-- 1 bakerdn  27K Jul 13 11:25 remoteEntry.457435b4c1229552ec51.js
-rw-r--r-- 1 bakerdn  26K Jul 13 11:25 remoteEntry.457435b4c1229552ec51.js.map
-rw-r--r-- 1 bakerdn  26K Jul 13 11:25 remoteEntry.ee43757e5b4e61b5e80a.js.map
-rw-r--r-- 1 bakerdn  118 Jul 13 11:25 style.js

./venv/share/jupyter/labextensions/jupyterlab-theme-solarized-dark/themes:
total 17K
drwxr-xr-x 2 bakerdn 4 Jul 13 11:25 jupyterlab-theme-solarized-dark/

./venv/share/jupyter/labextensions/jupyterlab-theme-solarized-dark/themes/jupyterlab-theme-solarized-dark:
total 10K
-rw-r--r-- 1 bakerdn 18K Jul 13 11:25 index.css
-rw-r--r-- 1 bakerdn   0 Jul 13 11:25 index.js
```

`package.json` and `install.json` came directly from the repo. `build_log.json` appears generated.

There are several generated files in `static` that I haven't determined where they come from.

In the `themes` directory, the `index.js` file is empty but the `index.css` has many lines of CSS. It appears to be a flattened version of the CSS files in the `style` directory in the repo. In `style`, there is an `index.css` file that has one line, `import './base.css';`. In the `base.css` file there is `@import './variables.css';` followed by some additional CSS code. Finally, in `variables.css` there is additional CSS code with no more `@import` statements. All this CSS appears flattened in `themes/index.css`.

### node_modules

Looking at the files in `./venv/share/jupyter/lab/staging/node_modules/`, they all seem to be old and probably were populated when jupyterlab was installed. I don't think these are relevant to the theme extension.

### site-packages

Note: We can skip `./venv/lib/python3.9/site-packages/nbclassic/static/components/codemirror/theme/solarized.css` as it appears to be installed with jupyterlab.

Looking in the `site-packages/jupyterlab_theme_solarized_dark` we see:

```shell
$ ls -FhoAR .
.:
total 52K
-rw-r--r-- 1 bakerdn 321 Jul 13 11:25 __init__.py
drwxr-xr-x 4 bakerdn   6 Jul 13 11:25 labextension/
drwxr-xr-x 2 bakerdn   4 Jul 13 11:25 __pycache__/
-rw-r--r-- 1 bakerdn 625 Jul 13 11:25 _version.py

./labextension:
total 52K
-rw-r--r-- 1 bakerdn  22K Jul 13 11:25 build_log.json
-rw-r--r-- 1 bakerdn 3.5K Jul 13 11:25 package.json
drwxr-xr-x 2 bakerdn   10 Jul 13 11:25 static/
drwxr-xr-x 3 bakerdn    3 Jul 13 11:25 themes/

./labextension/static:
total 72K
-rw-r--r-- 1 bakerdn 1.7K Jul 13 11:25 lib_index_js.88cfd94f93ca3056743b.js
-rw-r--r-- 1 bakerdn 1000 Jul 13 11:25 lib_index_js.88cfd94f93ca3056743b.js.map
-rw-r--r-- 1 bakerdn 1.7K Jul 13 11:25 lib_index_js.a9f045a011f6eaf91a60.js
-rw-r--r-- 1 bakerdn  985 Jul 13 11:25 lib_index_js.a9f045a011f6eaf91a60.js.map
-rw-r--r-- 1 bakerdn  27K Jul 13 11:25 remoteEntry.457435b4c1229552ec51.js
-rw-r--r-- 1 bakerdn  26K Jul 13 11:25 remoteEntry.457435b4c1229552ec51.js.map
-rw-r--r-- 1 bakerdn  26K Jul 13 11:25 remoteEntry.ee43757e5b4e61b5e80a.js.map
-rw-r--r-- 1 bakerdn  118 Jul 13 11:25 style.js

./labextension/themes:
total 17K
drwxr-xr-x 2 bakerdn 4 Jul 13 11:25 jupyterlab-theme-solarized-dark/

./labextension/themes/jupyterlab-theme-solarized-dark:
total 10K
-rw-r--r-- 1 bakerdn 18K Jul 13 11:25 index.css
-rw-r--r-- 1 bakerdn   0 Jul 13 11:25 index.js

./__pycache__:
total 18K
-rw-r--r-- 1 bakerdn 616 Jul 13 11:25 __init__.cpython-39.pyc
-rw-r--r-- 1 bakerdn 772 Jul 13 11:25 _version.cpython-39.pyc
```

`__init__.py` and `_version.py` are exact copies from the repo with compiled byte code in the `__pycache__` directory. We find the same files in `labextension` as we did in `./venv/share/jupyter/labextensions/jupyterlab-theme-solarized-dark`. I'm not certain as to why they exist in both places and the documentation only discusses what happens to javascript files and not what happens to python files.

**Comment by djacu** [comment]
Something important from the [documentation](https://jupyterlab.readthedocs.io/en/stable/user/directories.html#jupyterlab-build-process). You can find the yarn script used by `jlpm` [here](https://github.com/jupyterlab/jupyterlab/blob/b4bc105f1b53a1a40b7b8faaca8ca65a1fa01e6f/jupyterlab/staging/yarn.js).

> The build process uses a specific yarn version with a default working combination of npm packages stored in a yarn.lock file shipped with JupyterLab. Those package source urls point to the default yarn registry. However, if you defined your own yarn registry in the yarn configuration, the default yarn registry will be replaced by your custom registry. If you then switch back to the default yarn registry, you will need to clean your staging folder before building:
```
jupyter lab clean
jupyter lab build
```

**Comment by djacu** [comment]
### Overview
I am looking at the [jupyterlab-theme-solarized-dark](https://github.com/AllanChain/jupyterlab-theme-solarized-dark) repo again and seeing what is involved in the development build.

There is this note:
> The jlpm command is JupyterLab's pinned version of [yarn](https://yarnpkg.com/) that is installed with JupyterLab. You may use yarn or npm in lieu of jlpm below.

The yarn script JupyterLab uses is committed in the repo. It appears to be an older version and it appears that yarn 1.x is in maintenance and not actively being developed. I am uncertain what would happen if a newer version of yarn was used.

```shell
$ node /nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab/staging/yarn.js --version
1.21.1
```

### Dev Build
There are several steps to build the extension but I'm going to focus on `jlpm build` from the documentation copied below.

```shell
# Clone the repo to your local environment
# Change directory to the jupyterlab_theme_solarized_dark directory
# Install package in development mode
pip install -e .
# Link your development version of the extension with JupyterLab
jupyter labextension develop . --overwrite
# Rebuild extension Typescript source after making changes
jlpm build
```

This is from the `scripts` attribute in the `package.json` file.
```json
"build": "jlpm build:lib && jlpm build:labextension:dev",
"build:prod": "jlpm clean && jlpm build:lib && jlpm build:labextension",
"build:labextension": "jupyter labextension build .",
"build:labextension:dev": "jupyter labextension build --development True .",
"build:lib": "tsc",
```

If we break down what `jlpm build` is, it looks something like this

```shell
jlpm build
jlpm jlpm build:lib && jlpm build:labextension:dev
jlpm jlpm tsc && jlpm jupyter labextension build --development True .
```

I know that `jlpm` essentially is an alias for `node yarn.js` where the yarn script is the pinned version in the JupyterLab repo. So it can be rewritten as:

```shell
node yarn.js tsc && node ...
```

Now to figure out what the `...` is.

### Python

I dug through JupyterLab and traitlets repos to understand how the code works.

#### Class Hierarchy

jupyter labextension build
* calls BuildLabExtensionApp.launch_instance
  * BuildLabExtensionApp
    * is a subclass of BaseExtensionApp
      * is a subclass of JupyterApp
        * is a subclass of traitlets.Application
          * defines the @classmethod launch_instance
```python
def launch_instance(cls, argv=None, **kwargs):
  """Launch a global instance of this Application
  If a global instance already exists, this reinitializes and starts it
  """
  app = cls.instance(**kwargs)
  app.initialize(argv)
  app.start()
```

BaseExtensionApp defines start and calls run_task
    BuildLabExtensionApp defines run_task which calls build_labextension
    BuildLabExtensionApp passes self.extra_args[0] to build_labextension
    self.extra_args is defined in Application. The path to figure out what it is exactly is convoluted but I'm going to assume it's whatever is not an option (e.g. for `jupyter labextension build --development True .` the `.` would be extra_args).

#### build_labextension

build_labextension has several arguments -- the first is positional and the rest are kwargs.
* path=self.extra_args[0] - which should be `.`
* logger=self.log - not sure where self.log is defined yet
* the last 4 are CLI arguments
* development is `False` if not set
* static_url is `''` if not set
* source_map is `False` if not set
* core_path defaults to a `package.json` file located [here](https://github.com/jupyterlab/jupyterlab/blob/b4bc105f1b53a1a40b7b8faaca8ca65a1fa01e6f/jupyterlab/staging/package.json) if not set

build_labextension builds an shell command, `arguments`, and runs it with `subprocess.check_call` with an additional argument `cwd=ext_path` which sets the working directory.
* `arguments = ["node", builder, "--core-path", core_path, ext_path]`
  * `builder = _ensure_builder(ext_path, core_path)`
    * See below for info on `_ensure_builder`
  * `ext_path = osp.abspath(path)`
  * `cwd=ext_path`
    * `ext_path = osp.abspath(path)` so it's the `.` from the command line argument

#### _ensure_builder

I am trying to see what the output is of `_ensure_builder`. I am using the following as input arguments to the function.

```python
ext_path=/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab/staging/package.json
core_path=/home/bakerdn/scratch/jupyterlab-theme-solarized-dark/
```

However, I ran into an issue when trying to call it from the Python REPL.

```python
>>> from jupyterlab import federated_labextensions
>>> federated_labextensions._ensure_builder('/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab/staging/package.json', '/home/bakerdn/scratch/jupyterlab-theme-solarized-dark/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab/federated_labextensions.py", line 258, in _ensure_builder
    with open(osp.join(ext_path, "package.json")) as fid:
NotADirectoryError: [Errno 20] Not a directory: '/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab/staging/package.json/package.json'
>>> federated_labextensions._ensure_builder('/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab/staging/', '/home/bakerdn/scratch/jupyterlab-theme-solarized-dark/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab/federated_labextensions.py", line 274, in _ensure_builder
    subprocess.check_call(["jlpm"], cwd=ext_path)
  File "/nix/store/6wiycdxh63mk4krdd75db0hshicna6yy-python3-3.10.4/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/nix/store/6wiycdxh63mk4krdd75db0hshicna6yy-python3-3.10.4/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/nix/store/6wiycdxh63mk4krdd75db0hshicna6yy-python3-3.10.4/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/6wiycdxh63mk4krdd75db0hshicna6yy-python3-3.10.4/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'jlpm'
```

So I'm going to call each line one-by-one. I'll skip on steps that cause Errors for the time being.

```python
>>> import os.path as osp
>>> import json
>>> ext_path = '/home/bakerdn/scratch/jupyterlab-theme-solarized-dark/'
>>> core_path = '/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab/staging/'
>>> with open(osp.join(core_path, "package.json")) as fid:
...   core_data = json.load(fid)
... 
>>> with open(osp.join(ext_path, "package.json")) as fid:
...   ext_data = json.load(fid)
... 
>>> depVersion1 = core_data["devDependencies"]["@jupyterlab/builder"]
>>> depVersion1
'^3.1.0'
>>> depVersion2 = ext_data.get("devDependencies", dict()).get("@jupyterlab/builder")
>>> depVersion2
'^3.4.3'
>>> depVersion2 = depVersion2 or ext_data.get("dependencies", dict()).get("@jupyterlab/builder")
>>> depVersion2
'^3.4.3'
>>> '/' in depVersion2
False
```

Scratch that! I had the arguments backwards!

```python
>>> federated_labextensions._ensure_builder('/home/bakerdn/scratch/jupyterlab-theme-solarized-dark/', '/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab/staging/')
'/home/bakerdn/scratch/jupyterlab-theme-solarized-dark/node_modules/@jupyterlab/builder/lib/build-labextension.js'
```

The code that was failing before was this line:

```python
if not osp.exists(osp.join(ext_path, "node_modules")):
  subprocess.check_call(["jlpm"], cwd=ext_path)
```

It checks for a `node_modules` directory in the project top level directory and essentually runs `node yarn.js` on it to populate the `node_modules` directory. You can see the before an after below.

```shell
$ lse
total 286K
-rw-r--r-- 1 bakerdn   86 Jul 14 22:57 CHANGELOG.md
-rw-r--r-- 1 bakerdn  223 Jul 14 22:57 install.json
drwxr-xr-x 2 bakerdn    4 Jul 14 22:57 jupyterlab_theme_solarized_dark/
-rw-r--r-- 1 bakerdn 1.5K Jul 14 22:57 LICENSE
-rw-r--r-- 1 bakerdn  425 Jul 14 22:57 MANIFEST.in
-rw-r--r-- 1 bakerdn 3.4K Jul 14 22:57 package.json
-rw-r--r-- 1 bakerdn  659 Jul 14 22:57 pyproject.toml
-rw-r--r-- 1 bakerdn 4.1K Jul 14 22:57 README.md
-rw-r--r-- 1 bakerdn 1.9K Jul 14 22:57 RELEASE.md
-rw-r--r-- 1 bakerdn 2.9K Jul 14 22:57 setup.py
drwxr-xr-x 2 bakerdn    3 Jul 14 22:57 src/
drwxr-xr-x 2 bakerdn    6 Jul 14 22:57 style/
-rw-r--r-- 1 bakerdn  554 Jul 14 22:57 tsconfig.json
-rw-r--r-- 1 bakerdn 285K Jul 14 22:57 yarn.lock
```

```shell
$ node /nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab/staging/yarn.js
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@jupyterlab/application > @jupyterlab/ui-components@3.4.3" has unmet peer dependency "react@^17.0.1".
warning "@jupyterlab/application > @lumino/coreutils@1.12.0" has unmet peer dependency "crypto@1.0.1".
warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.1.0" has unmet peer dependency "typanion@*".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
Done in 5.59s.
```

```shell
$ lse
total 319K
-rw-r--r--   1 bakerdn   86 Jul 14 22:57 CHANGELOG.md
-rw-r--r--   1 bakerdn  223 Jul 14 22:57 install.json
drwxr-xr-x   2 bakerdn    4 Jul 14 22:57 jupyterlab_theme_solarized_dark/
-rw-r--r--   1 bakerdn 1.5K Jul 14 22:57 LICENSE
-rw-r--r--   1 bakerdn  425 Jul 14 22:57 MANIFEST.in
drwxr-xr-x 697 bakerdn  698 Jul 14 22:57 node_modules/
-rw-r--r--   1 bakerdn 3.4K Jul 14 22:57 package.json
-rw-r--r--   1 bakerdn  659 Jul 14 22:57 pyproject.toml
-rw-r--r--   1 bakerdn 4.1K Jul 14 22:57 README.md
-rw-r--r--   1 bakerdn 1.9K Jul 14 22:57 RELEASE.md
-rw-r--r--   1 bakerdn 2.9K Jul 14 22:57 setup.py
drwxr-xr-x   2 bakerdn    3 Jul 14 22:57 src/
drwxr-xr-x   2 bakerdn    6 Jul 14 22:57 style/
-rw-r--r--   1 bakerdn  554 Jul 14 22:57 tsconfig.json
-rw-r--r--   1 bakerdn 285K Jul 14 22:57 yarn.lock
```

### Conclusion

I believe the following command can be broken down as shown below.

```shell
jupyter labextension build --development True .
```

```shell
node yarn.js <ext_path>
node build-labextension.js --core-path <core_path> <ext_path>
```

Where `yarn.js` is the yarn script pinned in the jupyterlab repo.
Where 'build-labextension.js' is created in extension project top level directory under `node_modules/@jupyterlab/builder/lib`.
Where <core_path> refers to the `jupyterlab/staging/` in the jupyterlab repo.
Where <ext_path> refers to the extension project top level directory.

There are some additional checks in `_ensure_builder` such as `_test_overlap` (and more) but this covers the main path of the code.
