### ISSUE TITLE
jupyter-lab has incorrect paths.

### ISSUE THREAD

**Issue by djacu** [tweag/jupyterWith#226]
**Describe the bug**
After starting jupyterlab, the LabApp and ServerApp throw errors when starting the server and trying to create notebooks. Also the creation of the notebook fails and no file is generated. It seems from the errors that jupyter-lab is trying to write to a path in the nix store that is read only.

**To Reproduce**
Build the project, run `jupyter-lab`, try to create a notebook.

```shell
$ nix build .#example_jupyterlab -L
$ ./result/bin/jupyter-lab
```

**Expected behavior**
No errors and notebooks are created and written to file.

**Environment**
 - NixOS-22.11
 - commit: 687f8fde67c8c375ec025e339d3bac98db081740

**Additional context**
Errors generated while starting the server.

```shell
$ ./result/bin/jupyter-lab
[I 2022-07-22 15:00:48.455 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-07-22 15:00:48.472 LabApp] JupyterLab extension loaded from /nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab
[I 2022-07-22 15:00:48.472 LabApp] JupyterLab application directory is /nix/store/4xyz6l1rc06y0bsgc4q86yqq9iwr3v1i-python3.10-jupyterlab-3.4.3/share/jupyter/lab
[I 2022-07-22 15:00:48.475 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-07-22 15:00:48.476 ServerApp] Serving notebooks from local directory: /home/bakerdn/tweag/jupyterWith
[I 2022-07-22 15:00:48.476 ServerApp] Jupyter Server 1.17.1 is running at:
[I 2022-07-22 15:00:48.476 ServerApp] http://localhost:8888/lab?token=567ec2c826a9f18730fe83a5284b62bcc28571a65e54ea47
[I 2022-07-22 15:00:48.476 ServerApp]  or http://127.0.0.1:8888/lab?token=567ec2c826a9f18730fe83a5284b62bcc28571a65e54ea47
[I 2022-07-22 15:00:48.476 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2022-07-22 15:00:48.479 ServerApp] No web browser found: could not locate runnable browser.
[C 2022-07-22 15:00:48.479 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/bakerdn/.local/share/jupyter/runtime/jpserver-3730586-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=567ec2c826a9f18730fe83a5284b62bcc28571a65e54ea47
     or http://127.0.0.1:8888/lab?token=567ec2c826a9f18730fe83a5284b62bcc28571a65e54ea47
[I 2022-07-22 15:00:51.828 LabApp] 302 GET /lab? (127.0.0.1) 2.40ms
[I 2022-07-22 15:00:59.380 ServerApp] 302 GET / (127.0.0.1) 0.79ms
/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/IPython/paths.py:70: UserWarning: IPython parent '/' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
[W 2022-07-22 15:01:01.182 LabApp] Could not determine jupyterlab build status without nodejs
[W 2022-07-22 15:01:02.050 ServerApp] 500 PUT /lab/api/workspaces/default?1658527262045 (127.0.0.1): [Errno 30] Read-only file system: '/nix/store/2jvpbzfv06a8mxqmxdr62zmi6lvqlbw5-jupyter-dir/config/lab'
[W 2022-07-22 15:01:02.050 LabApp] [Errno 30] Read-only file system: '/nix/store/2jvpbzfv06a8mxqmxdr62zmi6lvqlbw5-jupyter-dir/config/lab'
[E 2022-07-22 15:01:02.051 LabApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab?",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
    }
[E 2022-07-22 15:01:02.051 LabApp] 500 PUT /lab/api/workspaces/default?1658527262045 (127.0.0.1) 1.35ms referer=http://localhost:8888/lab?
[W 2022-07-22 15:01:02.615 ServerApp] 500 PUT /lab/api/workspaces/default?1658527262608 (127.0.0.1): [Errno 30] Read-only file system: '/nix/store/2jvpbzfv06a8mxqmxdr62zmi6lvqlbw5-jupyter-dir/config/lab'
[W 2022-07-22 15:01:02.615 LabApp] [Errno 30] Read-only file system: '/nix/store/2jvpbzfv06a8mxqmxdr62zmi6lvqlbw5-jupyter-dir/config/lab'
[E 2022-07-22 15:01:02.617 LabApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
    }
[E 2022-07-22 15:01:02.617 LabApp] 500 PUT /lab/api/workspaces/default?1658527262608 (127.0.0.1) 4.34ms referer=http://localhost:8888/lab
```

Errors generated when trying to create a notebook.

```shell
[I 2022-07-22 15:01:27.570 ServerApp] Creating new notebook in 
[W 2022-07-22 15:01:27.594 ServerApp] The signatures database cannot be opened; maybe it is corrupted or encrypted. You may need to rerun your notebooks to ensure that they are trusted to run Javascript. The old signatures database has been renamed to /nix/store/2jvpbzfv06a8mxqmxdr62zmi6lvqlbw5-jupyter-dir/data/nbsignatures.db.bak and a new one has been created.
[W 2022-07-22 15:01:27.594 ServerApp] Failed commiting signatures database to disk. You may need to move the database file to a non-networked file system, using config option `NotebookNotary.db_file`. Using in-memory signatures database for the remainder of this session.
[I 2022-07-22 15:01:27.594 ServerApp] Writing notebook-signing key to /nix/store/2jvpbzfv06a8mxqmxdr62zmi6lvqlbw5-jupyter-dir/data/notebook_secret
[E 2022-07-22 15:01:27.595 ServerApp] Error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/nix/store/2jvpbzfv06a8mxqmxdr62zmi6lvqlbw5-jupyter-dir/data/notebook_secret'
    Traceback (most recent call last):
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/traitlets/traitlets.py", line 645, in get
        value = obj._trait_values[self.name]
    KeyError: 'secret'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 434, in save
        self.check_and_sign(nb, path)
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 651, in check_and_sign
        self.notary.sign(nb)
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/nbformat/sign.py", line 461, in sign
        signature = self.compute_signature(nb)
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/nbformat/sign.py", line 426, in compute_signature
        hmac = HMAC(self.secret, digestmod=self.digestmod)
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/traitlets/traitlets.py", line 686, in __get__
        return self.get(obj, cls)
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/traitlets/traitlets.py", line 648, in get
        default = obj.trait_defaults(self.name)
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/traitlets/traitlets.py", line 1752, in trait_defaults
        return self._get_trait_default_generator(names[0])(self)
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/traitlets/traitlets.py", line 1132, in __call__
        return self.func(*args, **kwargs)
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/nbformat/sign.py", line 403, in _secret_default
        self._write_secret_file(secret)
      File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/nbformat/sign.py", line 413, in _write_secret_file
        with open(self.secret_file, "wb") as f:
    OSError: [Errno 30] Read-only file system: '/nix/store/2jvpbzfv06a8mxqmxdr62zmi6lvqlbw5-jupyter-dir/data/notebook_secret'
[W 2022-07-22 15:01:27.596 ServerApp] 500 POST /api/contents?1658527287569 (127.0.0.1): Unexpected error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/nix/store/2jvpbzfv06a8mxqmxdr62zmi6lvqlbw5-jupyter-dir/data/notebook_secret'
[W 2022-07-22 15:01:27.596 ServerApp] Unexpected error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/nix/store/2jvpbzfv06a8mxqmxdr62zmi6lvqlbw5-jupyter-dir/data/notebook_secret'
[E 2022-07-22 15:01:27.596 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
    }
[E 2022-07-22 15:01:27.596 ServerApp] 500 POST /api/contents?1658527287569 (127.0.0.1) 26.59ms referer=http://localhost:8888/lab
```

**Comment by djacu** [comment]
This bug is not present in commit 8dd7db7ba989f85b48935a0033a1144316d21881

**Comment by djacu** [comment]
This bug is tied to the results in https://github.com/tweag/jupyterWith/issues/213#issuecomment-1176624167. It is _not_ explicitly mentioned in the documentation but jupyterlab will use jupyter's config directory as a root for user settings and workspaces if certain environment variables are not set.

In short, we need to set `JUPYTERLAB_SETTINGS_DIR`, and `JUPYTERLAB_WORKSPACES_DIR` to a writable directory or else jupyterlab will not start properly. 

See below for supporting documentation
[JupyterLab Directories](https://jupyterlab.readthedocs.io/en/stable/user/directories.html#jupyterlab-user-settings-directory)
[Jupyter Common Files and Locations](https://docs.jupyter.org/en/latest/use/jupyter-directories.html#configuration-files)
