### ISSUE TITLE
ipython has no writable path

### ISSUE THREAD

**Issue by djacu** [tweag/jupyterWith#230]
**Describe the bug**
JupyterLab issues warnings about IPython directory not being writable. The IPython kernel appears to function fine despite the error but other kernels crash.

**To Reproduce**
Build the project, run `jupyter-lab`, try to create a notebook.

```shell
$ nix build .#example_jupyterlab -L
$ ./result/bin/jupyter-lab
```

Open the web app and start one of the example kernel notebooks.

**Expected behavior**
No warnings and kernels should operate without crashing.

**Environment**
 - NixOS-22.11
 - commit: c10c8ad8d46983de1d7bc2db996389106827bca4

**Additional context**
Discussion in following comments.

**Comment by djacu** [comment]
## Errors from the current commit.

The server starts up as normal.

```shell
$ ./result/bin/jupyter-lab
[I 2022-07-25 17:28:14.270 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-07-25 17:28:14.288 LabApp] JupyterLab extension loaded from /nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab
[I 2022-07-25 17:28:14.289 LabApp] JupyterLab application directory is /nix/store/4xyz6l1rc06y0bsgc4q86yqq9iwr3v1i-python3.10-jupyterlab-3.4.3/share/jupyter/lab
[I 2022-07-25 17:28:14.292 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-07-25 17:28:14.292 ServerApp] Serving notebooks from local directory: /home/bakerdn/tweag/jupyterWith
[I 2022-07-25 17:28:14.292 ServerApp] Jupyter Server 1.17.1 is running at:
[I 2022-07-25 17:28:14.293 ServerApp] http://localhost:8888/lab?token=6c9605545f9685254b7bfbef642ed6aaa6c80c63b72e5f35
[I 2022-07-25 17:28:14.293 ServerApp]  or http://127.0.0.1:8888/lab?token=6c9605545f9685254b7bfbef642ed6aaa6c80c63b72e5f35
[I 2022-07-25 17:28:14.293 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2022-07-25 17:28:14.296 ServerApp] No web browser found: could not locate runnable browser.
[C 2022-07-25 17:28:14.296 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/bakerdn/.local/share/jupyter/runtime/jpserver-314111-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=6c9605545f9685254b7bfbef642ed6aaa6c80c63b72e5f35
     or http://127.0.0.1:8888/lab?token=6c9605545f9685254b7bfbef642ed6aaa6c80c63b72e5f35
```

However, after opening the web application, warnings start to show up.

```shell
[I 2022-07-25 17:30:55.555 ServerApp] 302 GET / (127.0.0.1) 1.76ms
/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/IPython/paths.py:70: UserWarning: IPython parent '/' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
[W 2022-07-25 17:30:57.319 LabApp] Could not determine jupyterlab build status without nodejs
```

Opening a notebook with the example ipython kernel appears to work okay. Statements do evaluate properly. It still gives warnings about the IPython directory.
```shell
[I 2022-07-25 17:32:28.312 ServerApp] Creating new notebook in 
[I 2022-07-25 17:32:28.342 ServerApp] Writing notebook-signing key to .jupyter/data/notebook_secret
[I 2022-07-25 17:32:28.588 ServerApp] Kernel started: 13cc3e2c-4a9b-433e-aae6-cd2796248cfd
/nix/store/c8g6rnp740ryxb1fc8iay9dh909bnp17-python3-3.10.4-env/lib/python3.10/site-packages/IPython/paths.py:70: UserWarning: IPython parent '/' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
[W 2022-07-25 17:32:29.244 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7f28913872b0>
```

Trying to start a different kernel causes severe issues.

```shell
[I 2022-07-25 17:36:45.114 ServerApp] Creating new notebook in 
[I 2022-07-25 17:36:45.327 ServerApp] Kernel started: e8747df8-e58f-416f-b354-0c8c44224842
/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/IPython/paths.py:70: UserWarning: IPython parent '/' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
Traceback (most recent call last):
  File "/nix/store/6wiycdxh63mk4krdd75db0hshicna6yy-python3-3.10.4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/6wiycdxh63mk4krdd75db0hshicna6yy-python3-3.10.4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ansible_kernel/__main__.py", line 6, in <module>
    IPKernelApp.launch_instance(kernel_class=AnsibleKernel)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/traitlets/config/application.py", line 975, in launch_instance
    app.initialize(argv)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 681, in initialize
    self.init_kernel()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 528, in init_kernel
    kernel = kernel_factory(
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/traitlets/config/configurable.py", line 551, in instance
    inst = cls(*args, **kwargs)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ansible_kernel/kernel.py", line 239, in __init__
    self.do_execute_play(self.default_play)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ansible_kernel/kernel.py", line 674, in do_execute_play
    self.start_ansible_playbook()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ansible_kernel/kernel.py", line 708, in start_ansible_playbook
    if self.process_message(msg.message):
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ansible_kernel/kernel.py", line 449, in process_message
...
Repeats the last 2 method calls until the recursion limit is reached.
...
    if self.process_message(msg.message):
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ansible_kernel/kernel.py", line 449, in process_message
    self.start_ansible_playbook()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ansible_kernel/kernel.py", line 708, in start_ansible_playbook
    if self.process_message(msg.message):
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ansible_kernel/kernel.py", line 448, in process_message
    self.rewrite_ports()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/ansible_kernel/kernel.py", line 293, in rewrite_ports
    playbook = yaml.load(f.read(), Loader=yaml.FullLoader)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/scanner.py", line 255, in fetch_more_tokens
    return self.fetch_plain()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/scanner.py", line 679, in fetch_plain
    self.tokens.append(self.scan_plain())
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/scanner.py", line 1277, in scan_plain
    start_mark = self.get_mark()
  File "/nix/store/qgcb3fz2zp6sa681j8k91pbrn57zgyy9-python3-3.10.4-env/lib/python3.10/site-packages/yaml/reader.py", line 116, in get_mark
    return Mark(self.name, self.index, self.line, self.column,
RecursionError: maximum recursion depth exceeded
```

**Comment by djacu** [comment]
## Possible Cause of Error
In the function, `mkJupyterlabInstance`, we set the `IPYTHONDIR` environment variable to a non-existent directory. According to the [IPython documentation](https://ipython.readthedocs.io/en/stable/config/intro.html#the-ipython-directory), this directory needs to exist and likely be writable as IPython stores its files -- config, command history and extensions -- in the directory.

**Comment by djacu** [comment]
## Not setting the `IPYTHONDIR` variable

Removing the line `--set IPYTHONDIR "/path-not-set" \` from the flake does not work. After rebuilding, the jupyter-lab environment fails to start.

```shell
$ ./result/bin/jupyter-lab
Traceback (most recent call last):
  File "/nix/store/4xyz6l1rc06y0bsgc4q86yqq9iwr3v1i-python3.10-jupyterlab-3.4.3/bin/.jupyter-lab-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 584, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 554, in initialize_server
    serverapp.initialize(
  File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
  File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2435, in initialize
    super().initialize(argv=argv)
  File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
  File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_core/application.py", line 244, in initialize
    self.migrate_config()
  File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_core/application.py", line 174, in migrate_config
    migrate()
  File "/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_core/migrate.py", line 241, in migrate
    with open(os.path.join(env["jupyter_config"], "migrated"), "w", encoding="utf-8") as f:
OSError: [Errno 30] Read-only file system: '/nix/store/mkgm8n6yp0645s8fpsfjsap3nwlnxwyq-jupyter-dir/config/migrated'
```

**Comment by djacu** [comment]
## Setting `IPYTHONDIR` to a different location

Similar to what was done in #229, setting `IPYTHONDIR` to a location that is writable, fixes the issue. 

```shell
--set IPYTHONDIR ".jupyter/.ipython" \
```

As with the PR, this can be a temporary fix until a permanent controlled location can be established.

Starting up the server the first time does give a warning.

```shell
$ ./result/bin/jupyter-lab
[I 2022-07-25 18:10:27.104 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-07-25 18:10:27.122 LabApp] JupyterLab extension loaded from /nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab
[I 2022-07-25 18:10:27.122 LabApp] JupyterLab application directory is /nix/store/4xyz6l1rc06y0bsgc4q86yqq9iwr3v1i-python3.10-jupyterlab-3.4.3/share/jupyter/lab
[I 2022-07-25 18:10:27.125 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-07-25 18:10:27.126 ServerApp] Serving notebooks from local directory: /home/bakerdn/tweag/jupyterWith
[I 2022-07-25 18:10:27.126 ServerApp] Jupyter Server 1.17.1 is running at:
[I 2022-07-25 18:10:27.126 ServerApp] http://localhost:8888/lab?token=b7cb7756eea0c16b90d0d5cbbca57519c926e454a4d8e264
[I 2022-07-25 18:10:27.126 ServerApp]  or http://127.0.0.1:8888/lab?token=b7cb7756eea0c16b90d0d5cbbca57519c926e454a4d8e264
[I 2022-07-25 18:10:27.126 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2022-07-25 18:10:27.129 ServerApp] No web browser found: could not locate runnable browser.
[C 2022-07-25 18:10:27.129 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/bakerdn/.local/share/jupyter/runtime/jpserver-350846-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=b7cb7756eea0c16b90d0d5cbbca57519c926e454a4d8e264
     or http://127.0.0.1:8888/lab?token=b7cb7756eea0c16b90d0d5cbbca57519c926e454a4d8e264
/nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/IPython/paths.py:70: UserWarning: IPython parent '.jupyter' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
[W 2022-07-25 18:10:31.968 LabApp] Could not determine jupyterlab build status without nodejs
```

It appears that IPython is looking to write in the `.jupyter` directory before it exists yet. Looking at the `.jupyter` folder, we see that the `.ipython` folder does not exist.

```shell
$ ls -FhoA .jupyter/
total 17K
drwxr-xr-x 3 bakerdn 3 Jul 25 18:10 lab/
```

So this might be a race condition or things happening in a particular order. Wherever the final location of `IPYTHONDIR` is set, it must have a writable directory existing before starting the server. Also, despite the documentation saying:

> If set, this environment variable should be the path to a directory, which IPython will use for user data. IPython will create it if it does not exist.

It appears there are some limitations.


Running it again after the first produces no warnings and now the `ipython` folder exists.

```shell
$ ls -FhoA .jupyter/
total 34K
drwxr-xr-x 2 bakerdn 2 Jul 25 18:11 .ipython/
drwxr-xr-x 3 bakerdn 3 Jul 25 18:10 lab/
```

```shell
$ ./result/bin/jupyter-lab
[I 2022-07-25 18:11:01.427 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-07-25 18:11:01.446 LabApp] JupyterLab extension loaded from /nix/store/cl3hbbkpahmpq7v3lmk1ps15mp01wg2r-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab
[I 2022-07-25 18:11:01.446 LabApp] JupyterLab application directory is /nix/store/4xyz6l1rc06y0bsgc4q86yqq9iwr3v1i-python3.10-jupyterlab-3.4.3/share/jupyter/lab
[I 2022-07-25 18:11:01.449 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-07-25 18:11:01.450 ServerApp] Serving notebooks from local directory: /home/bakerdn/tweag/jupyterWith
[I 2022-07-25 18:11:01.450 ServerApp] Jupyter Server 1.17.1 is running at:
[I 2022-07-25 18:11:01.450 ServerApp] http://localhost:8888/lab?token=3442be4699557bd0ab94b8e085f04dfe46f241d9626da3f6
[I 2022-07-25 18:11:01.450 ServerApp]  or http://127.0.0.1:8888/lab?token=3442be4699557bd0ab94b8e085f04dfe46f241d9626da3f6
[I 2022-07-25 18:11:01.450 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2022-07-25 18:11:01.454 ServerApp] No web browser found: could not locate runnable browser.
[C 2022-07-25 18:11:01.454 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/bakerdn/.local/share/jupyter/runtime/jpserver-351144-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=3442be4699557bd0ab94b8e085f04dfe46f241d9626da3f6
     or http://127.0.0.1:8888/lab?token=3442be4699557bd0ab94b8e085f04dfe46f241d9626da3f6
[W 2022-07-25 18:14:37.303 LabApp] Could not determine jupyterlab build status without nodejs
```

No issues running the IPython kernel

```shell
[I 2022-07-25 18:20:07.381 ServerApp] Creating new notebook in 
[I 2022-07-25 18:20:07.409 ServerApp] Writing notebook-signing key to .jupyter/data/notebook_secret
[I 2022-07-25 18:20:07.629 ServerApp] Kernel started: a1c1c1ba-0905-4c7e-98bf-124530093559
[W 2022-07-25 18:20:08.287 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7fa86e234880>
```

The ansible did run into the same issue but had no warnings about the IPython directory.
