### ISSUE TITLE
jupyterlab terminal doesn't work in docker environment

### ISSUE THREAD

**Issue by MMesch** [tweag/jupyterWith#25]
when clicking on "terminal" in the jupyterlab launcher in the docker environment, an exception is thrown:

```
[E 22:45:19.596 LabApp] Uncaught exception POST /api/terminals?1551307519574 (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/terminals?1551307519574', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/nix/store/wfnwy4byyfgdymzl98rx65w6vps25r1q-python3.7-tornado-5.1/lib/python3.7/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/nix/store/wfnwy4byyfgdymzl98rx65w6vps25r1q-python3.7-tornado-5.1/lib/python3.7/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/nix/store/shr9l7bl21y9i4ibsvx5mqb8y1jk5jy8-python3.7-notebook-5.7.2/lib/python3.7/site-packages/notebook/terminal/api_handlers.py", line 16, in post
        name, _ = self.terminal_manager.new_named_terminal()
      File "/nix/store/siq6c0n6mllbq5jlf50hgwv17dkpdh7x-python3.7-terminado-0.8.1/lib/python3.7/site-packages/terminado/management.py", line 319, in new_named_terminal
        term = self.new_terminal()
      File "/nix/store/siq6c0n6mllbq5jlf50hgwv17dkpdh7x-python3.7-terminado-0.8.1/lib/python3.7/site-packages/terminado/management.py", line 171, in new_terminal
        pty = PtyProcessUnicode.spawn(argv, env=env, cwd=options.get('cwd', None))
      File "/nix/store/mmca1wgjind71kqqypc0c3riqbas0ahp-python3.7-ptyprocess-0.6.0/lib/python3.7/site-packages/ptyprocess/ptyprocess.py", line 209, in spawn
        command_with_path = which(command)
      File "/nix/store/ydk0mfpvn9smcmn72wc9i20slv1d2b79-python3-3.7.2/lib/python3.7/shutil.py", line 1135, in which
        if os.path.dirname(cmd):
      File "/nix/store/ydk0mfpvn9smcmn72wc9i20slv1d2b79-python3-3.7.2/lib/python3.7/posixpath.py", line 156, in dirname
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
[W 22:45:19.600 LabApp] Unhandled error
```

we should probably install a shell.

**Comment by djacu** [comment]
Closing out old issues with no activity in preparation for migration to the `next` branch.
