### ISSUE TITLE
[Bug]: Permission denied error

### ISSUE THREAD

**Issue by sepiabrown** [tweag/jupyterWith#394]
### Current Behavior

I'm following the [Getting Started](https://jupyterwith.tweag.io/getting-started/?query=%25env) tutorial.
`nix run` works well for the first time.
But at the second time of `nix run` fails with
```
PermissionError: [Errno 13] Permission denied: '/nix/store/94xvsmmr4pnkabnm2hgn5rndb6w6q0mg-jupyter-dir/config/migrated'
```
### Expected Behavior

No error.

### Steps To Reproduce

mkdir my-project
cd my-project
nix flake init --template github:tweag/jupyterWith
nix run
nix run

### OS

```shell
- system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-1160.49.1.el7.x86_64, CentOS Linux, 7 (Core), nobuild`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.1`
 - channels(sepiabrown): `"nixos-22.11, nixpkgs"`
 - nixpkgs: `/home/sepiabrown/.nix-defexpr/channels/nixpkgs`
```

### Version

NixOS: 22.11.20220914.1158501 (Raccoon)
jupyterWith: [778ec10](https://github.com/tweag/jupyterWith/commit/778ec10b5ed23153b4552418e85fdba9321d59cc)

### Additional Context

What I observed is that after first `nix run`, the directory `path-not-set` is created at `/`. The existence of the directory seems to cause the error because when I erase the directory, the error disappears. (So every time I want to restart jupyterlab, I have to erase the directory..)

### Relevant log output

```
sepiabrown@localhost:~/test/new2JupyterWith$ nix run
warning: Using saved setting for 'extra-substituters = https://tweag-jupyter.cachix.org' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = tweag-jupyter.cachix.org-1:UtNH4Zs6hVUFpFBTLaA4ejYavPo5EFFqgd7G7FxGW9g=' from ~/.local/share/nix/trusted-settings.json.
jupyterWith does not need build JupyterLab. Starting...
Traceback (most recent call last):
  File "/nix/store/k27s4d0sxq8l4jy04rbn2ydgjjk4jy56-python3.10-jupyterlab-3.5.0/bin/.jupyter-lab-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/7vsg7dg5c195ad5c0zfv73f0ilks2pkj-python3-3.10.8-env/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 584, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/nix/store/7vsg7dg5c195ad5c0zfv73f0ilks2pkj-python3-3.10.8-env/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 554, in initialize_server
    serverapp.initialize(
  File "/nix/store/7vsg7dg5c195ad5c0zfv73f0ilks2pkj-python3-3.10.8-env/lib/python3.10/site-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
  File "/nix/store/7vsg7dg5c195ad5c0zfv73f0ilks2pkj-python3-3.10.8-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2435, in initialize
    super().initialize(argv=argv)
  File "/nix/store/7vsg7dg5c195ad5c0zfv73f0ilks2pkj-python3-3.10.8-env/lib/python3.10/site-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
  File "/nix/store/7vsg7dg5c195ad5c0zfv73f0ilks2pkj-python3-3.10.8-env/lib/python3.10/site-packages/jupyter_core/application.py", line 244, in initialize
    self.migrate_config()
  File "/nix/store/7vsg7dg5c195ad5c0zfv73f0ilks2pkj-python3-3.10.8-env/lib/python3.10/site-packages/jupyter_core/application.py", line 174, in migrate_config
    migrate()
  File "/nix/store/7vsg7dg5c195ad5c0zfv73f0ilks2pkj-python3-3.10.8-env/lib/python3.10/site-packages/jupyter_core/migrate.py", line 241, in migrate
    with open(os.path.join(env["jupyter_config"], "migrated"), "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: '/nix/store/94xvsmmr4pnkabnm2hgn5rndb6w6q0mg-jupyter-dir/config/migrated'
```

**Comment by djacu** [comment]
Hey @sepiabrown 

I think I remember running into this issue as well a while back. We put in some fixes to address this. Have you tried it recently? It shouldn't happen any more.
