### ISSUE TITLE
[Bug]: documentation for options is broken 

### ISSUE THREAD

**Issue by anpin** [tweag/jupyterWith#565]
### Current Behavior

![image](https://github.com/user-attachments/assets/d071ca7f-d112-4148-8f51-686a47164dec)
![image](https://github.com/user-attachments/assets/c3bf4248-f9c0-494f-9cc8-c278a26c07d2)

### Expected Behavior

options are shown

### Steps To Reproduce

https://jupyenv.io/documentation/options/

### OS

```shell
irrelevant
```

### Version

master

### Additional Context

lib.mdDoc was removed in https://github.com/tweag/jupyenv/pull/563

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at options.js:151:51
    at NodeList.forEach (<anonymous>)
    at initializePage (options.js:149:6)
    at options/:711:5
```
```

**Comment by anpin** [comment]
seems like [options.py](https://github.com/tweag/jupyenv/blob/55e42c3dea87d3c1e3e9dfde28df637e88d6bd39/docs/python-scripts/options.py)  is no longer working

Tagging @garbas and @djacu since they are the only authors

**Comment by anpin** [comment]
I found that `nest_options_in_dom` function is producing empty DOM. However both  `nix build .\#lib.x86_64-linux.options.optionsJSON` and  `html = md.render(commonmark)` in above options.py seems to yield the same format as before.

**Comment by phanirithvij** [comment]
cc @GTrunSec

**Comment by phanirithvij** [comment]
as of now I get

```js
Uncaught TypeError: getNextSibling(...) is undefined
    initializePage https://jupyenv.io/javascripts/options.js:151
    initializePage https://jupyenv.io/javascripts/options.js:149
    <anonymous> https://jupyenv.io/documentation/options/:711
[options.js:151:21](https://jupyenv.io/javascripts/options.js)
```

I comment that line locally and rebuild `nix build .#packages.x86_64-linux.docs --accept-flake-config`

and I still can't view the options (double checked disabled cache in the browser, and no new errors in the console)
